name: tb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.1=py310h5764c6d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - azure-core==1.35.0
      - azure-identity==1.23.0
      - certifi==2025.7.9
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cramjam==2.11.0
      - cryptography==45.0.5
      - cycler==0.12.1
      - distro==1.9.0
      - fastparquet==2024.11.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - jiter==0.10.0
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - langchain-core==0.3.68
      - langchain-openai==0.3.27
      - langsmith==0.4.4
      - matplotlib==3.10.3
      - msal==1.32.3
      - msal-extensions==1.3.1
      - numpy==2.2.6
      - openai==1.93.2
      - orjson==3.10.18
      - packaging==24.2
      - pandas==2.3.1
      - pillow==11.3.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - sam-mtb-utils==0.1.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - zstandard==0.23.0
prefix: /anaconda/envs/tb
